// src/components/NavBar.tsx
import { useState, useEffect } from 'react';
import { Menu, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useTranslation } from 'react-i18next';
import { motion, AnimatePresence } from 'framer-motion';

export const NavBar = () => {
  const [isScrolled, setIsScrolled] = useState(false);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  const { t } = useTranslation();

  const navItems = [
    { key: 'about', href: '#about' },
    { key: 'skills', href: '#skills' },
    { key: 'services', href: '#services' },
    { key: 'experience', href: '#experience' },
    { key: 'projects', href: '#projects' },
    { key: 'testimonials', href: '#testimonials' },
    { key: 'contact', href: '#contact' },
  ]

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 50)
    }
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, [])

  const scrollToSection = (href: string) => {
    const element = document.querySelector(href);
    if(element) {
      element.scrollIntoView({ behavior: 'smooth' });
      setIsMobileMenuOpen(false);
    }
  }

  return (
    <motion.nav initial={{ y: -100}} animate={{ y: 0 }} 
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
        isScrolled 
          ? 'bg-background/80 backdrop-blur-md shadow-custom-md border-b border-border' 
          : 'bg-transparent'
        }`}>
      <div className='container-custom'>
        <div className='flex items-center justify-between h-16 px-4'>
          <motion.div 
            className='font-bold text-xl text-gradient cursor-pointer'
            whileHover={{ scale: 1.05}}
            onClick={() => scrollToSection('#hero')}
          >
            Portfolio
          </motion.div>

          <div className='hidden md:flex items-center space-x-8'>
            {navItems.map((item) => (
              <button key={item.key} 
                onClick={() => scrollToSection(item.href)}
                className='text-foreground hover:text-primary transition-colors hover-underline'
              >
                {t(`nav.${item.key}`)}
              </button>
            ))}
          </div>

          <div className='flex items-center space-x-2'>
            {/* Mobile menu button */}
            <Button
              variant='ghost'
              size='icon'
              className='md:hidden'
              onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}>
                { isMobileMenuOpen ? <X className='h-6 w-6' /> : <Menu className='h-6 w-6' />}
            </Button>
          </div>
        </div>

        {/* Mobile Navigation */}
        <AnimatePresence>
          {isMobileMenuOpen && (
            <motion.div
              initial={{ opacity: 0, height: 0}}
              animate={{ opacity: 1, height: 'auto'}}
              exit={{ opacity: 0, height: 0}}
              className='md:hidden bg-background/95 backdrop-blur-md border-t border-border'
            >
              <div className='py-4 space-y-2'>
                {
                  navItems.map((item) => (
                    <button 
                      key={item.key}
                      onClick={() => scrollToSection(item.href)}
                      className='block w-full text-left px-4 py-2 text-foreground hover:text-primary hover:bg-secondary transition-colors'
                    >
                      {t(`nav.${item.key}`)}
                    </button>
                  ))
                }
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </motion.nav>
  )
}

// src/components/NavBar.vue
<script setup>
  import { ref } from 'vue'

  const menu = ref([
    {
      name: 'Services',
      href: '#services'
    },
    {
      name: 'About Me',
      href: '#about'
    },
    {
      name: 'Skills',
      href: '#skills'
    },
    {
      name: 'Projects',
      href: '#projects'
    },
    {
      name: 'Testimonials',
      href: '#testimonials'
    },
    {
      name: 'Contact',
      href: '#contact'
    }
  ])

  const isMenuOpen = ref(false)
  const scrollToSection = (href) => {
    isMenuOpen.value = false
    const section = document.querySelector(href)
    if(section){
      section.scrollIntoView({ behavior: 'smooth' })
    }
  }
</script>

<template>
  <header class="flex justify-between items-center p-6 bg-opacity-50 relative z-20">
    <div class="text-white text-3xl font-bold">LOGO</div>
    <!-- Mobile Toggle button -->
    <div class="md:hidden z-30">
      <button type="button" 
        class="block focus:outline-none"
        @click="isMenuOpen = !isMenuOpen"
      >
        <span v-if="isMenuOpen" class="text-5xl">
          <img src="https://img.icons8.com/ios-filled/100/ffffff/delete-sign.png" alt="close" width="50" height="50">
        </span>
        <span v-else class="text-5xl">
          <img src="https://img.icons8.com/ios-filled/100/ffffff/menu--v6.png" alt="menu" width="50" height="50">
        </span>
      </button>
    </div>
    <!-- NavBar Link -->
    <nav :class="['fixed inset-0 z-20 flex flex-col items-center justify-center md:relative md:bg-transparent md:flex md:justify-between md:flex-row',
      isMenuOpen ? 'block' : 'hidden'
    ]">
      <ul class="flex flex-col items-center space-y-12 md:flex-row md:space-x-5 md:space-y-0">
        <li v-for="item in menu" :key="item.name">
          <a :href="item.href" 
            class="block text-white transition hover:text-primary ease-linear text-2xl md:text-lg"
            @click="scrollToSection(item.href)"
          >{{ item.name }}</a>
        </li>
      </ul>
    </nav>
  </header>
</template>
